name: Bug report
description: Report an issue that should be fixed
title: "[bug] "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: ocv version
      description: What version of ocv are you using?
      placeholder: run ocv --version
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug you encountered
      placeholder: What happened?
    validations:
      required: true
